"""Build the Gloaming site into docs/, for GitHub Pages.

Six pages - a landing page and a privacy policy, in English, Ukrainian and
Russian - from ONE template each. Hand-writing six files means six files
drifting: a section added to the English page and forgotten in the other two is
not a thing anyone notices until a Ukrainian reader is missing a paragraph.
Here the structure is written once and the strings are a table, so a missing
translation is a KeyError at build time rather than a hole on a live page.

The palette and the type are lifted from Theme.kt so the site and the app agree.
Two themes, as the app has: the page follows the OS by default and the toggle
overrides it, which is Settings' own Dusk / Dawn / system choice.

FONTS. Neither bundled font has a single Cyrillic glyph - figtree.ttf carries
391 codepoints and baloo2.ttf 856, Latin both. So the Ukrainian and Russian
pages CANNOT be set in Figtree, and the stack names Golos Text after it: the
browser falls back per glyph, so Latin words keep the brand face and Cyrillic
gets a family designed for it, rather than whatever the OS happens to reach for.
The app has the same gap and no such fallback; see the note in the site commit.

URLS ARE LOAD-BEARING. docs/privacy-policy.html is the address given to Google
Play, so that file must keep its name and its place at the root. The translated
copies live under uk/ and ru/ rather than the English one moving.

Run from anywhere:  python3 tools/build_site.py
"""
import os
from PIL import Image

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
DOCS = os.path.join(ROOT, 'docs')

GITHUB = 'https://github.com/jemcik/Gloaming'
EFFECTIVE = '4 September 2026'

# ── the shared stylesheet ──────────────────────────────────────────────────
# Tokens are Theme.kt's Dawn and Dusk. They were copy-pasted into two pages
# before this file existed, which at six pages would have been twelve copies.
CSS = """/* Generated by tools/build_site.py - edit there, not here. */

:root {
  /* Dawn, from Theme.kt */
  --surface: #FDFDFD;
  --raise:   #E4E5E2;
  --veil:    #DCDEDA;
  --line:    #C5C4BD;
  --outline: #ACACA5;
  --ink:     #1E1B18;
  --ink-mid: #514A43;
  --state:   #435B7A;
  --fill:    #596F8B;
  --on-fill: #FFFFFF;

  /* Arc - the dial's sweep, night to dawn */
  --night: #2F4260;
  --dusk:  #4E6480;
  --ember: #B2622D;
  --dawn:  #F6A06B;

  --body: "Figtree", "Golos Text", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  --wrap: 46rem;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="dawn"]) {
    --surface: #20242A;
    --raise:   #2F353D;
    --veil:    #383E46;
    --line:    #49505A;
    --outline: #61666E;
    --ink:     #EAEBED;
    --ink-mid: #C7CDD7;
    --state:   #B0C3E0;
    --fill:    #566479;
    --on-fill: #DDE9FF;
  }
}

:root[data-theme="dusk"] {
  --surface: #20242A;
  --raise:   #2F353D;
  --veil:    #383E46;
  --line:    #49505A;
  --outline: #61666E;
  --ink:     #EAEBED;
  --ink-mid: #C7CDD7;
  --state:   #B0C3E0;
  --fill:    #566479;
  --on-fill: #DDE9FF;
}

* { box-sizing: border-box; }

/* The base size goes on the ROOT, not on body. Every other size here is in rem,
   and rem resolves against the root - so with 17px on body and 16px still on
   html, `h3 { font-size: 1rem }` meant "the same as body" and rendered 16px
   against body's 17px: a feature title SMALLER than its own paragraph. */
html { scroll-behavior: smooth; font-size: 17px; }
@media (prefers-reduced-motion: reduce) {
  html { scroll-behavior: auto; }
  * { animation: none !important; transition: none !important; }
}

body {
  margin: 0;
  background: var(--surface);
  color: var(--ink);
  font-family: var(--body);
  line-height: 1.65;
  -webkit-font-smoothing: antialiased;
}

/* ── chrome ── */

/* THE BAR SHARES THE CONTENT COLUMN'S EDGES. It was 62rem against main's 46rem,
   so the language switcher sat a clear 8rem to the right of the text it was
   meant to line up with, and the mark the same distance to the left. One width
   for both, and the masthead reads as the top of the page rather than as a
   separate strip laid over it. */
.bar {
  display: flex; align-items: center; gap: 1rem; flex-wrap: wrap; row-gap: .9rem;
  max-width: var(--wrap); margin: 0 auto; padding: 1.6rem 1.5rem .35rem;
}
/* The brand IS the lockup now - the app's mark at a size the crescent is
   visible in, and the name at headline weight. It used to be 38px and 1.2rem
   sitting next to a 2.7rem tagline, which is how the page came to introduce
   itself in the smallest type on the screen. */
.brand {
  display: flex; align-items: center; gap: clamp(.55rem, 2vw, .85rem);
  font-weight: 800; font-size: clamp(1.25rem, 4.4vw, 2.2rem);
  letter-spacing: -.03em; line-height: 1;
  color: var(--ink); text-decoration: none;
}
.brand img {
  width: clamp(38px, 9vw, 62px); height: clamp(38px, 9vw, 62px); flex: none;
}
/* The masthead now has TWO things competing for one row, and on a 360px phone -
   which is as common a width as any - the mark, the name, three language
   buttons and the theme button do not all fit. Measured at 375px: they fit with
   the 16px gap and NOTHING to spare, so the next narrower phone is over the
   edge. `.brand` cannot shrink below its icon plus the word "Gloaming", so with
   wrap on, the switcher drops to a line of its own and stays right-aligned
   rather than the two being squashed into each other. Costs nothing at any
   width where they do fit. */
.bar-end { margin-left: auto; display: flex; align-items: center; gap: .4rem; }

.langs { display: flex; gap: .15rem; }
.langs a, .theme {
  font: inherit; font-size: .82rem; font-weight: 600;
  color: var(--ink-mid); background: none; border: 1px solid transparent;
  border-radius: 6px; padding: .3rem .55rem; text-decoration: none; cursor: pointer;
}
.langs a:hover, .theme:hover { color: var(--ink); border-color: var(--line); }
.langs a[aria-current="page"] { color: var(--on-fill); background: var(--fill); }
.langs a:focus-visible, .theme:focus-visible {
  outline: 2px solid var(--state); outline-offset: 2px;
}
.theme { display: inline-flex; align-items: center; gap: .35rem; }
.theme svg { width: 15px; height: 15px; }

/* The switcher says the language's OWN NAME where there is room, and falls back
   to a code where there is not - measured at 375px, where "English Українська
   Русский" clipped and pushed the theme button off the screen entirely. The
   theme button loses its word at the same breakpoint for the same reason:
   «Як у системі» is wider than all three languages together. */
.sm { display: none; }
@media (max-width: 34rem) {
  .lg { display: none; }
  .sm { display: inline; }
  .theme .theme-name { display: none; }
}

/* The masthead misses ONE ROW BY THREE PIXELS on the phone it was tested on.
   The Honor is 1256px at density 560, so 359 CSS px, and mark + name + three
   language buttons + the theme button came to 362 - the switcher dropped to a
   line of its own, correct and ugly, for the sake of 3px. Everything here gives
   back a little: the gap, the brand's floor, and the buttons' side padding,
   which is where the room actually is - .55rem either side of three buttons is
   53px of nothing. The horizontal PADDING is untouchable, because it is what
   holds the bar on the text column's edges. */
@media (max-width: 26rem) {
  .bar { gap: .7rem; }
  .bar-end { gap: .3rem; }
  .langs a, .theme { padding: .3rem .42rem; }
  .brand { font-size: 1.2rem; gap: .5rem; }
  .brand img { width: 36px; height: 36px; }
}

/* ── layout ── */

main { max-width: var(--wrap); margin: 0 auto; padding: 1.5rem 1.5rem 5rem; }
section { margin-top: 3.25rem; }

/* Smaller than it was - 2.7rem/2rem - and the floor is what matters. The root
   is 17px, so the old 2rem floor drew the headline at 34px, and «конфиденциальности»
   measures 369px there against a 311px column on a 359px phone: the Russian
   privacy title ran off the screen. 1.6rem puts that word at 295px. break-word
   is the backstop for a 320px screen, where no headline size that is still a
   headline will fit it. */
h1 {
  font-size: clamp(1.6rem, 6vw, 2.35rem); font-weight: 700;
  line-height: 1.12; letter-spacing: -.02em; margin: 0;
  text-wrap: balance; overflow-wrap: break-word;
}
h2 {
  font-size: 1.35rem; font-weight: 700; letter-spacing: -.01em;
  margin: 0 0 .9rem; padding-top: 1.5rem; border-top: 1px solid var(--line);
  text-wrap: balance;
}
h3 { font-size: 1rem; font-weight: 700; margin: 0 0 .2rem; }
p { margin: 0 0 1rem; color: var(--ink-mid); }
.lead { font-size: 1.1rem; color: var(--ink); margin-top: 1rem; }
strong { color: var(--ink); font-weight: 600; }
a { color: var(--state); text-underline-offset: 2px; }

/* ── hero ── */

.hero { padding-top: 1rem; }
.sweep {
  height: 7px; border-radius: 4px; margin: 1.75rem 0 0;
  background: linear-gradient(90deg, var(--night) 0%, var(--dusk) 42%,
                                     var(--ember) 76%, var(--dawn) 100%);
}
.cta { display: flex; flex-wrap: wrap; gap: .65rem; margin-top: 1.75rem; }
.btn {
  display: inline-block; text-decoration: none; font-weight: 600; font-size: .95rem;
  padding: .6rem 1.15rem; border-radius: 8px;
  background: var(--fill); color: var(--on-fill); border: 1px solid var(--fill);
}
.btn.ghost { background: none; color: var(--ink); border-color: var(--line); }
.btn:focus-visible { outline: 2px solid var(--state); outline-offset: 2px; }

/* ── screenshots ── */

.shots {
  display: grid; grid-template-columns: repeat(3, 1fr); gap: .9rem;
  margin-top: 2.5rem;
}
.shot {
  padding: 0; border: 1px solid var(--line); border-radius: 10px;
  background: none; cursor: zoom-in; overflow: hidden; display: block;
}
.shot img { width: 100%; display: block; }
.shot:focus-visible { outline: 2px solid var(--state); outline-offset: 2px; }

/* One theme's shots at a time, on the same three-state rule as the colours:
   bare :root is light, the media query covers "system", the stamp wins. */
.shot.dark { display: none; }
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="dawn"]) .shot.light { display: none; }
  :root:not([data-theme="dawn"]) .shot.dark { display: block; }
}
:root[data-theme="dusk"] .shot.light { display: none; }
:root[data-theme="dusk"] .shot.dark { display: block; }
:root[data-theme="dawn"] .shot.light { display: block; }
:root[data-theme="dawn"] .shot.dark { display: none; }

@media (max-width: 34rem) { .shots { grid-template-columns: repeat(2, 1fr); } }

/* ── the viewer ── */

.viewer {
  position: fixed; inset: 0; z-index: 50;
  background: rgba(0, 0, 0, .82);
  display: flex; align-items: center; justify-content: center;
  padding: 2rem 1rem; cursor: zoom-out;
}
.viewer img {
  max-width: min(92vw, 420px); max-height: 92vh;
  border-radius: 12px; box-shadow: 0 24px 60px rgba(0, 0, 0, .5);
}
/* FIT-TO-HEIGHT STOPS BEING AN ENLARGEMENT ON A SHORT WINDOW. These are phone
   screenshots at 1:2.24, and the thumbnail is ~233px wide on any viewport past
   --wrap - so 92vh only beats it above ~570px of window, and at 460px, which is
   what a docked browser pane gives you, clicking to enlarge made the picture
   SMALLER than the one clicked. Measured, not reasoned about. Below the point
   where fitting the height still buys a third again, size by WIDTH and let the
   overlay scroll; flex-start rather than centre, or the overflowing top is
   unreachable. */
@media (max-height: 780px) {
  .viewer { align-items: flex-start; overflow: auto; }
  .viewer img { max-height: none; }
}
.viewer[hidden] { display: none; }

/* The arrows are position:FIXED, not absolute. The overlay scrolls on a short
   window - see the media query above - and absolute children scroll away with
   the picture, which puts the controls somewhere off-screen exactly when the
   picture is too big to see at once. Fixed inside a fixed parent anchors to the
   viewport, so they hold still. Nothing here may carry a transform or that
   stops being true. */
.vnav {
  position: fixed; top: 50%; transform: translateY(-50%); z-index: 2;
  width: 46px; height: 46px; border-radius: 50%; padding: 0;
  display: grid; place-items: center; cursor: pointer;
  background: rgba(255, 255, 255, .13); color: #fff;
  border: 1px solid rgba(255, 255, 255, .26);
}
.vnav svg { width: 22px; height: 22px; }
.vnav:hover { background: rgba(255, 255, 255, .24); }
.vnav:focus-visible { outline: 2px solid #fff; outline-offset: 3px; }
/* The picture is centred and rarely wider than 420px, so an arrow pinned to the
   VIEWPORT edge sits half a screen away from the thing it pages through. The
   script measures the image and sets --vnav-x to put them just off its edges;
   the clamp is what they fall back to before that runs. One variable does both
   sides, because a centred image has the same inset either way. */
.vnav.prev { left: var(--vnav-x, clamp(.5rem, 4vw, 2.5rem)); }
.vnav.next { right: var(--vnav-x, clamp(.5rem, 4vw, 2.5rem)); }
.viewer.solo .vnav, .viewer.solo .vcount { display: none; }
/* A PILL, not bare text. The counter is fixed and the picture scrolls under it
   whenever the picture is taller than the window - which on a phone is always -
   so "1 / 3" was landing on top of whatever the screenshot happened to say
   there. Seen on the Honor: it sat across the app's own "Bedtime starts the day
   before." Its own background is the only thing that makes it legible over an
   image it cannot predict. */
.vcount {
  position: fixed; left: 50%; transform: translateX(-50%); bottom: 1.1rem;
  margin: 0; z-index: 2; width: max-content;
  padding: .2rem .65rem; border-radius: 999px;
  background: rgba(0, 0, 0, .62); backdrop-filter: blur(2px);
  color: rgba(255, 255, 255, .92);
  font-size: .82rem; font-weight: 600; font-variant-numeric: tabular-nums;
}

/* ── feature list ── */

.feats { display: flex; flex-direction: column; gap: 0; }
.feat { padding: .95rem 0; border-bottom: 1px solid var(--veil); }
.feat:last-child { border-bottom: 0; }
.feat p { margin: 0; }

/* ── notes ── */

.note {
  background: var(--raise); border-radius: 9px; padding: 1.1rem 1.25rem;
}
.note p:last-child { margin-bottom: 0; }

ul { padding-left: 1.15rem; margin: 0 0 1rem; }
li { color: var(--ink-mid); margin-bottom: .5rem; }

code {
  font-family: ui-monospace, "SF Mono", Menlo, monospace;
  font-size: .86em; background: var(--raise); color: var(--ink);
  padding: .1em .35em; border-radius: 3px;
}

footer {
  max-width: var(--wrap); margin: 0 auto;
  padding: 1.5rem 1.5rem 4rem; border-top: 1px solid var(--line);
  font-size: .88rem; color: var(--ink-mid);
}
footer a { color: var(--state); }
"""

# ── theme toggle ───────────────────────────────────────────────────────────
# Applied from an inline head script too, so the page never paints the wrong
# theme first. Three states because Settings has three; "system" is a stored
# value like the others rather than the absence of one.
JS = """// Generated by tools/build_site.py - edit there, not here.
(function () {
  var KEY = 'gloaming-theme', ORDER = ['system', 'dawn', 'dusk'];
  function read() {
    try { return localStorage.getItem(KEY) || 'system'; } catch (e) { return 'system'; }
  }
  function apply(v) {
    var r = document.documentElement;
    if (v === 'system') r.removeAttribute('data-theme'); else r.setAttribute('data-theme', v);
  }
  function label(btn, v) {
    btn.setAttribute('aria-label', btn.dataset['label' + v.charAt(0).toUpperCase() + v.slice(1)] || v);
    btn.querySelector('.theme-name').textContent =
      btn.dataset['name' + v.charAt(0).toUpperCase() + v.slice(1)] || v;
  }
  // Click a screenshot to see it properly. The thumbnail is a 520px copy; the
  // viewer loads the full capture, which is the only place it is worth the
  // bytes. Escape closes, so does clicking anywhere - the whole overlay is the
  // target, because hunting for a small × is the thing people complain about.
  //
  // It is a GALLERY, not a single picture: once one is open the arrows and the
  // left/right keys move through the set without closing it, because closing
  // and reopening to see the next of three is the thing that makes a lightbox
  // feel like a document viewer.
  document.addEventListener('DOMContentLoaded', function () {
    var viewer = document.querySelector('.viewer');
    if (viewer) {
      var img = viewer.querySelector('img');
      var count = viewer.querySelector('.vcount');
      var shots = [], at = -1;

      // Only the shots the CURRENT THEME draws. Both themes are in the markup
      // and one is display:none, so a naive querySelectorAll walks six and
      // navigates into pictures that are not on the page.
      var live = function () {
        return [].filter.call(document.querySelectorAll('.shot'), function (b) {
          return b.offsetParent !== null;
        });
      };
      // Neighbours are fetched ahead. These are 150-240kB captures, so without
      // this every arrow press blanks the overlay while the next one loads.
      var warm = function (i) {
        if (!shots.length) return;
        [i - 1, i + 1].forEach(function (n) {
          var b = shots[(n + shots.length) % shots.length];
          if (b) { new Image().src = b.dataset.full; }
        });
      };
      var show = function (i) {
        at = (i + shots.length) % shots.length;
        var b = shots[at];
        img.src = b.dataset.full;
        img.alt = b.getAttribute('aria-label') || '';
        count.textContent = (at + 1) + ' / ' + shots.length;
        place();
        warm(at);
      };
      var step = function (d) { if (shots.length > 1) show(at + d); };

      // Put the arrows against the PICTURE. Measured rather than computed: the
      // image is capped by width on a short window and by height on a tall one,
      // so its rendered width is not something the stylesheet can name without
      // hard-coding the screenshots' aspect ratio. Falls back to the CSS clamp
      // whenever there is nothing to measure yet.
      var place = function () {
        if (viewer.hidden) return;
        var r = img.getBoundingClientRect();
        if (!r.width) return;
        var btn = viewer.querySelector('.vnav');
        var w = btn ? btn.offsetWidth : 46;
        viewer.style.setProperty(
          '--vnav-x', Math.max(8, Math.round(r.left - 14 - w)) + 'px');
      };
      img.addEventListener('load', place);
      window.addEventListener('resize', place);

      // Hold the page still underneath. The overlay covers everything, so a
      // wheel over it scrolls a page nobody can see, and closing then lands
      // somewhere other than the screenshots you were just looking at. The
      // padding replaces the scrollbar's own width, or removing it shifts the
      // whole page sideways at the moment the viewer opens.
      var lock = function (on) {
        var d = document.documentElement;
        if (on) {
          var gap = window.innerWidth - d.clientWidth;
          d.style.overflow = 'hidden';
          if (gap > 0) d.style.paddingRight = gap + 'px';
        } else {
          d.style.overflow = '';
          d.style.paddingRight = '';
        }
      };

      document.querySelectorAll('.shot').forEach(function (b) {
        b.addEventListener('click', function () {
          shots = live();
          viewer.classList.toggle('solo', shots.length < 2);
          viewer.hidden = false;
          lock(true);
          show(shots.indexOf(b));
          // tabindex="-1" is what makes this line do anything: a plain div is
          // not focusable, so focus stayed on <body> and the dialog opened
          // without announcing itself.
          viewer.focus();
        });
      });

      var close = function () {
        viewer.hidden = true;
        lock(false);
        img.removeAttribute('src');
        // Back to the thumbnail SHOWING, not the one clicked. After three
        // arrow presses the picture on screen is not the one that opened the
        // viewer, and landing the keyboard back on that one is disorienting.
        var b = shots[at];
        shots = []; at = -1;
        if (b) b.focus();
      };
      viewer.addEventListener('click', close);
      viewer.querySelectorAll('.vnav').forEach(function (b) {
        b.addEventListener('click', function (e) {
          // The overlay closes on any click and the arrows sit inside it.
          e.stopPropagation();
          step(b.classList.contains('next') ? 1 : -1);
        });
      });
      document.addEventListener('keydown', function (e) {
        if (viewer.hidden) return;
        if (e.key === 'Escape') { close(); }
        else if (e.key === 'ArrowRight') { e.preventDefault(); step(1); }
        else if (e.key === 'ArrowLeft') { e.preventDefault(); step(-1); }
      });
    }

    var btn = document.querySelector('.theme');
    if (!btn) return;
    var cur = read();
    label(btn, cur);
    btn.addEventListener('click', function () {
      cur = ORDER[(ORDER.indexOf(cur) + 1) % ORDER.length];
      try { localStorage.setItem(KEY, cur); } catch (e) {}
      apply(cur);
      label(btn, cur);
    });
  });
})();
"""

HEAD_SCRIPT = ("<script>(function(){try{var v=localStorage.getItem('gloaming-theme');"
               "if(v&&v!=='system')document.documentElement.setAttribute('data-theme',v);}"
               "catch(e){}})();</script>")

FONTS = ('<link rel="preconnect" href="https://fonts.googleapis.com">'
         '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
         '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?'
         'family=Figtree:wght@400;600;700&family=Golos+Text:wght@400;600;700&display=swap">')

# The LABEL is the language's own name, not a code. "UK" is the correct ISO
# 639-1 code for Ukrainian and it is what <html lang> and the /uk/ path carry -
# but as a switcher label people read it as United Kingdom, whose ISO country
# code is not even UK, it is GB. "UA" would be a country code standing in for a
# language. A speaker recognizes their own language's name with nothing to
# decode, which is the entire job of a switcher.
LANGS = [('en', 'English', 'EN', ''), ('uk', 'Українська', 'UA', 'uk/'),
         ('ru', 'Русский', 'RU', 'ru/')]

# The three the page shows, in the order the app meets you: the dial, then what
# the night does to the screen, then what still gets through.
SHOTS = ['home', 'effects', 'allowed']
THEMES = ['light', 'dark']
# The captures are 1256 wide and the page draws them at about 200. A full-size
# PNG per shot per theme would be six of them and 1.4MB a page; these are the
# same pictures at a size the layout can use, in WebP. Measured on one shot:
# 157kB as a resized PNG, 51kB quantised to 128 colours, 26kB as WebP q82 - and
# a UI screenshot is flat colour and hard edges, which is where WebP is at its
# best. The FULL PNG is still what a click opens.
WEB_W = 520
WEB_Q = 82


def web_copies():
    """Downscale every capture once, into docs/screenshots/web/."""
    src = os.path.join(DOCS, 'screenshots')
    for lang, _, _, _ in LANGS:
        for theme in THEMES:
            for name in SHOTS:
                i = os.path.join(src, lang, theme, f'{name}.png')
                o = os.path.join(src, 'web', lang, theme, f'{name}.webp')
                os.makedirs(os.path.dirname(o), exist_ok=True)
                im = Image.open(i).convert('RGB')
                im.resize((WEB_W, round(im.height * WEB_W / im.width)), Image.LANCZOS) \
                    .save(o, 'WEBP', quality=WEB_Q, method=6)
    total = sum(os.path.getsize(os.path.join(dp, f))
                for dp, _, fs in os.walk(os.path.join(src, 'web')) for f in fs)
    print(f'screenshots/web/  18 copies at {WEB_W}px, {total // 1024}kB total')

# ── content ────────────────────────────────────────────────────────────────
# Every string for every page. A language missing a key fails the build.
T = {}

T['en'] = dict(
    htmllang='en',
    tagline='A bedtime app for Android that keeps its own schedule.',
    lead='Quiet your phone for whatever stretch of time you want — set up Do Not Disturb '
         'and the screen effects in one place. It all works even with the app closed, '
         'because it uses the Alarms and reminders permission you grant in the app. That '
         'guarantees it fires at exactly the time you set, and it never goes through the '
         'background job scheduler.',
    cta_get='Download the APK', cta_src='Source on GitHub',
    theme_system='System', theme_dawn='Dawn', theme_dusk='Dusk',
    viewer_label='Screenshots', viewer_prev='Previous screenshot',
    viewer_next='Next screenshot',
    shot_alts=['The home screen mid-window', 'How the screen looks during a window',
               'What is allowed to interrupt'],
    why_h='Why another bedtime app',
    why_p1='Android already has a bedtime mode. On a lot of phones it does not fire until '
           'you open the app that runs it — or it fires, but late. '
           'That mode is scheduled as a background job, and every vendor’s battery '
           'management gets a say in whether background jobs ever run. When something in '
           'that chain defers it there is no error and no notification — Do Not Disturb '
           'simply never comes on and the effects never apply.',
    why_p2='Gloaming does not use a background job. It asks for the Alarms and reminders '
           'permission — the one you grant inside the app — which the system guarantees '
           'will fire at the minute you set. The app holds its own Do Not Disturb rule and '
           'switches it itself, so bedtime happens whether or not the app is open.',
    what_h='What Gloaming does',
    feats=[
        ('A 24-hour dial',
         'One window, set by dragging either end around the dial or by tapping a time and '
         'picking it exactly. You choose the mornings you want to wake up on, not the '
         'evenings you go to bed: pick Saturday and the window runs from Friday evening '
         'to Saturday morning.'),
        ('It ends at your alarm',
         'Turn it on and the window follows whatever time your alarm is set for, instead '
         'of you keeping two schedules in step.'),
        ('A Quick Settings tile with three states',
         'Three faces, one meaning each. Hourglass — bedtime is on and waiting for its hour. Tick — a window is running right now. Gloaming’s own mark — bedtime is off. The tile never shows a tick for something that has not started.'),
        ('An allowlist for the window',
         'Who can call, who can message, conversations, repeat callers, reminders, '
         'calendar events, media. The screen reports the system’s current state, not the '
         'one the app switched on and assumes is in effect.'),
        ('Screen effects',
         'Grayscale, wallpaper dimming, dark theme, always-on display. Where the '
         'operating system does not let an app control an effect, the switch is not '
         'drawn at all, rather than offering one that lies.'),
        ('It checks rather than assumes',
         'Some phones freeze apps in the background, and the failure that causes is '
         'specific: the end of a window never fires, so bedtime does not end — whatever '
         'it switched on stays on into your day. Gloaming watches every end and says '
         'when one is late, with a button to the background setting that is usually the '
         'cause. It also asks once, eleven minutes after install, whether this phone '
         'delivers background alarms at all — silent unless the answer is no.'),
        ('A boot watch',
         'For phones that never tell apps the phone restarted: bedtime stays switched on '
         'while nothing behind it will fire. Gloaming notices.'),
    ],
    priv_h='What Gloaming doesn’t do',
    priv_p='Gloaming has no internet permission. Not “does not send data” — it cannot. '
           'There is no analytics, no advertising, no account and no third-party code. '
           'Your schedule and the app’s own log stay on the phone, and uninstalling '
           'removes them.',
    priv_link='Read the privacy policy',
    req_h='Requirements',
    req_p='Android 15 or newer. Two permissions, both granted from inside the app: '
          'notification policy access (for Do Not Disturb) and Alarms and reminders.',
    foot='Apache License 2.0 · ',
    foot_src='Source', foot_rel='Releases', foot_priv='Privacy policy', foot_iss='Report an issue',
    # privacy policy
    p_title='Privacy policy',
    p_sub='Gloaming for Android',
    p_lede='<strong>Gloaming collects nothing, stores everything on your device, and '
           'cannot send data anywhere.</strong> It does not request the <code>INTERNET</code> '
           'permission, so it has no network access of any kind — this is not a promise '
           'about intent, it is a restriction the operating system enforces.',
    p_h1='What is collected',
    p_1='Nothing. There is no analytics, no crash reporting, no advertising, no '
        'third-party SDK, no account and no sign-in. No personal or device data is '
        'gathered, transmitted, sold or shared with anyone.',
    p_h2='What is stored, and where',
    p_2='Everything Gloaming remembers stays in its own private storage on your phone:',
    p_2a='<strong>Your schedule and settings</strong> — the sleep window, the days it '
         'applies to, the interruption allowlist, the screen effects you enabled, and '
         'your theme and language choices.',
    p_2b='<strong>A journal</strong> — an on-device log of what the app did on each run, '
         'so a problem can be explained after the fact. It is written to the app’s own '
         'files directory and never leaves the phone on its own.',
    p_2c='Uninstalling Gloaming removes all of it. <strong>Reset Gloaming</strong>, inside '
         'the app, clears it without uninstalling.',
    p_h3='Diagnostics you choose to send',
    p_3='<strong>Send diagnostics</strong> gathers the journal, your schedule and what the '
        'system reports about the app’s Do Not Disturb rule into plain text, and hands '
        'it to Android’s share sheet. <strong>You choose the recipient</strong> — an '
        'email, a message, a note to yourself. Gloaming does not transmit it and has no way '
        'to; if you never use the button, nothing is ever produced. Read the text before '
        'sending it, as you would any message.',
    p_h4='Permissions, and why each exists',
    p_perms=[
        '<strong>Notification policy access</strong> — lets the app create and switch its '
        'own Do Not Disturb rule. This is what makes bedtime work. It grants no access to '
        'the content of your notifications, and Gloaming never reads them.',
        '<strong>Alarms and reminders</strong> (<code>SCHEDULE_EXACT_ALARM</code>) — lets '
        'the app start and end your window at exactly the time you set, while it is closed.',
        '<strong>Run at startup</strong> (<code>RECEIVE_BOOT_COMPLETED</code>) — lets it '
        'restore your schedule after a restart, so a reboot at 2am does not silently end '
        'bedtime.',
        '<strong>Modify system settings</strong> (<code>WRITE_SETTINGS</code>) — optional, '
        'and requested only if you use the always-on display control on a phone where that '
        'setting is reachable. Used solely to write that one display key.',
        '<code>WRITE_SECURE_SETTINGS</code> — declared but not grantable by an ordinary '
        'install; it can only be granted over adb, deliberately, by someone who wants the '
        'vendor always-on route. Without that grant the code path is inert.',
    ],
    p_4b='Gloaming requests no access to contacts, location, camera, microphone, storage, '
         'or the content of your messages or notifications.',
    p_h5='Children',
    p_5='Gloaming is a general-purpose utility. It is not directed at children, and since '
        'it collects no data it collects none from them either.',
    p_h6='Changes',
    p_6='If this policy ever changes it will change here, with the date below updated. The '
        'app is open source, so any change to what it actually does is visible in the '
        'commit history.',
    p_h7='Contact',
    p_7='Questions, or a report that something here is inaccurate: open an issue at',
    p_eff='Effective ' + EFFECTIVE + '. Source: ',
)

T['uk'] = dict(
    htmllang='uk',
    tagline='Режим сну для Android, який спрацьовує вчасно.',
    lead='Заспокойте свій телефон на бажаний проміжок часу — налаштуйте «Не турбувати» і '
         'екранні ефекти в одному зручному інтерфейсі. Усе працює, навіть якщо застосунок '
         'закритий: він користується дозволом «Будильники та нагадування», який ви надаєте '
         'в застосунку. Це дає гарантію спрацювання точно в заданий час і не проходить '
         'через планувальник фонових завдань.',
    cta_get='Завантажити APK', cta_src='Код на GitHub',
    theme_system='Як у системі', theme_dawn='Світла', theme_dusk='Темна',
    viewer_label='Знімки екрана', viewer_prev='Попередній знімок',
    viewer_next='Наступний знімок',
    shot_alts=['Головний екран посеред проміжку', 'Який вигляд має екран під час проміжку',
               'Що дозволено переривати'],
    why_h='Навіщо ще один застосунок для сну',
    why_p1='В Android уже є режим сну. На багатьох телефонах він не спрацьовує, доки ви не '
           'відкриєте застосунок, який ним керує, — або спрацьовує, але невчасно. Режим сну '
           'запланований як фонове завдання, а чи виконуються фонові завдання — вирішує '
           'керування батареєю кожного виробника. Якщо десь у цьому ланцюжку завдання '
           'відкладають, не буде ні помилки, ні сповіщення — «Не турбувати» просто не '
           'вмикається, а ефекти не застосовуються.',
    why_p2='Gloaming не користується фоновим завданням. Він просить дозвіл «Будильники та '
           'нагадування» — той самий, який ви надаєте в застосунку, — і система гарантує '
           'спрацювання в задану хвилину. Застосунок має власне правило «Не турбувати» і '
           'перемикає його сам, тож режим сну настає незалежно від того, відкритий '
           'застосунок чи ні.',
    what_h='Що вміє Gloaming',
    feats=[
        ('24-годинний циферблат',
         'Один проміжок: тягніть будь-який кінець по колу або торкніться часу й виберіть його '
         'точно. Ви обираєте не вечір, коли лягаєте, а ранок, коли хочете прокинутися: '
         'виберіть суботу — і проміжок триватиме з вечора п’ятниці до ранку суботи.'),
        ('Завершення за будильником',
         'Увімкніть — і проміжок сам підлаштується під час вашого будильника, замість того '
         'щоб вести два розклади паралельно.'),
        ('Плитка у швидких налаштуваннях із трьома станами',
         'Три вигляди, кожен з одним значенням. Пісочний годинник — режим сну увімкнено, він чекає своєї години. Галочка — проміжок триває просто зараз. Власний знак Gloaming — режим сну вимкнено. Плитка ніколи не показує галочку для того, що ще не почалося.'),
        ('Список винятків на час проміжку',
         'Хто може подзвонити, хто написати, розмови, повторні дзвінки, нагадування, події '
         'календаря, медіа. Екран показує поточний стан системи, а не той, який '
         'застосунок увімкнув і вважає чинним.'),
        ('Ефекти екрана',
         'Чорно-білий екран, притемнення шпалер, темна тема, always-on дисплей. Якщо '
         'операційна система не дозволяє застосунку керувати ефектом, перемикач не '
         'показується взагалі — краще жодного, ніж такий, що бреше.'),
        ('Він перевіряє, а не припускає',
         'Деякі телефони заморожують застосунки у фоні, і поломка при цьому конкретна: '
         'кінець проміжку не спрацьовує, тож режим сну не завершується — усе, що він '
         'увімкнув, лишається увімкненим уже вдень. Gloaming стежить за кожним кінцем і '
         'повідомляє, коли той запізнився, — із кнопкою до налаштування фонової роботи, '
         'яке зазвичай і є причиною. А ще одноразово, через одинадцять хвилин після '
         'встановлення, питає, чи доставляє цей телефон фонові сигнали взагалі, — і '
         'мовчить, якщо все гаразд.'),
        ('Спостереження за перезавантаженням',
         'Для телефонів, які не кажуть застосункам, що телефон перезавантажився: режим сну '
         'лишається увімкненим, але вже нічого не спрацює. Gloaming це помічає.'),
    ],
    priv_h='Чого Gloaming не робить',
    priv_p='У Gloaming немає дозволу на інтернет. Це не обіцянка не надсилати дані, а обмеження, яке забезпечує операційна система. Немає '
           'ні аналітики, ні реклами, ні акаунтів, ні стороннього коду. Ваш розклад і '
           'власний журнал застосунку лишаються на телефоні, а видалення застосунку '
           'прибирає їх.',
    priv_link='Читати політику приватності',
    req_h='Вимоги',
    req_p='Android 15 або новіший. Два дозволи, обидва надаються з самого застосунку: '
          'доступ до політики сповіщень (для «Не турбувати») і «Будильники та нагадування».',
    foot='Ліцензія Apache 2.0 · ',
    foot_src='Код', foot_rel='Релізи', foot_priv='Політика приватності',
    foot_iss='Повідомити про проблему',
    p_title='Політика приватності',
    p_sub='Gloaming для Android',
    p_lede='<strong>Gloaming нічого не збирає, зберігає все на вашому пристрої і не може '
           'нікуди надіслати дані.</strong> Він не запитує дозволу <code>INTERNET</code>, '
           'тож не має жодного доступу до мережі — це не обіцянка про наміри, а обмеження, '
           'яке забезпечує операційна система.',
    p_h1='Що збирається',
    p_1='Нічого. Немає аналітики, звітів про збої, реклами, сторонніх SDK, акаунтів і '
        'входу. Жодні особисті дані чи дані пристрою не збираються, не передаються, не '
        'продаються і ні з ким не діляться.',
    p_h2='Що зберігається і де',
    p_2='Усе, що Gloaming пам’ятає, лишається у його власному приватному сховищі на вашому '
        'телефоні:',
    p_2a='<strong>Ваш розклад і налаштування</strong> — проміжок сну, дні, у які він діє, '
         'список винятків, увімкнені екранні ефекти, а також вибрані тема й мова.',
    p_2b='<strong>Журнал</strong> — локальний запис того, що застосунок робив за кожен проміжок, щоб '
         'проблему можна було пояснити постфактум. Він пишеться у власну теку застосунку і '
         'ніколи не залишає телефон самостійно.',
    p_2c='Видалення Gloaming прибирає все це. <strong>Скинути Gloaming</strong>, усередині '
         'застосунку, очищає дані без видалення.',
    p_h3='Діагностика, яку ви надсилаєте самі',
    p_3='<strong>Надіслати діагностику</strong> збирає журнал, ваш розклад і те, що система '
        'повідомляє про правило «Не турбувати», у звичайний текст і передає його у вікно '
        'поширення Android. <strong>Одержувача обираєте ви</strong> — пошта, повідомлення, '
        'нотатка собі. Gloaming не передає це сам і не має такої змоги; якщо ви ніколи не '
        'натиснете кнопку, нічого й не буде створено. Прочитайте текст перед надсиланням, '
        'як і будь-яке повідомлення.',
    p_h4='Дозволи, і навіщо кожен',
    p_perms=[
        '<strong>Доступ до політики сповіщень</strong> — дозволяє застосунку створювати і '
        'перемикати власне правило «Не турбувати». Саме це змушує режим сну працювати. Він '
        'не дає доступу до вмісту ваших сповіщень, і Gloaming ніколи їх не читає.',
        '<strong>Будильники та нагадування</strong> (<code>SCHEDULE_EXACT_ALARM</code>) — '
        'дозволяє починати й завершувати ваш проміжок точно в заданий час, поки застосунок '
        'закритий.',
        '<strong>Запуск при старті</strong> (<code>RECEIVE_BOOT_COMPLETED</code>) — '
        'дозволяє відновити ваш розклад після перезавантаження, щоб перезапуск о другій '
        'ночі не завершив режим сну мовчки.',
        '<strong>Зміна системних налаштувань</strong> (<code>WRITE_SETTINGS</code>) — '
        'необов’язковий, запитується лише якщо ви користуєтеся керуванням always-on '
        'дисплеєм на телефоні, де це налаштування доступне. Використовується винятково для '
        'запису цього одного ключа.',
        '<code>WRITE_SECURE_SETTINGS</code> — оголошений, але його неможливо надати при '
        'звичайному встановленні; його видають лише через adb, свідомо, ті, хто хоче '
        'вендорський шлях до always-on. Без цього дозволу код лишається неактивним.',
    ],
    p_4b='Gloaming не запитує доступу до контактів, місцезнаходження, камери, мікрофона, '
         'сховища або вмісту ваших повідомлень чи сповіщень.',
    p_h5='Діти',
    p_5='Gloaming — інструмент загального призначення. Він не призначений для дітей '
        'і не збирає жодних даних — ні про них, ні про когось іншого.',
    p_h6='Зміни',
    p_6='Якщо ця політика колись зміниться, вона зміниться тут, із оновленою датою нижче. '
        'Застосунок має відкритий код, тож будь-яка зміна того, що він насправді робить, '
        'видима в історії комітів.',
    p_h7='Контакти',
    p_7='Питання або повідомлення про неточність тут: створіть issue за адресою',
    p_eff='Чинна з ' + EFFECTIVE + '. Код: ',
)

T['ru'] = dict(
    htmllang='ru',
    tagline='Режим сна для Android, который срабатывает вовремя.',
    lead='Успокойте свой телефон на нужный промежуток времени — настройте «Не беспокоить» '
         'и экранные эффекты в одном удобном интерфейсе. Всё работает, даже если приложение '
         'закрыто: оно пользуется разрешением «Будильники и напоминания», которое вы '
         'выдаёте в приложении. Это даёт гарантию срабатывания точно в заданное время и не '
         'проходит через планировщик фоновых задач.',
    cta_get='Скачать APK', cta_src='Код на GitHub',
    theme_system='Как в системе', theme_dawn='Светлая', theme_dusk='Тёмная',
    viewer_label='Снимки экрана', viewer_prev='Предыдущий снимок',
    viewer_next='Следующий снимок',
    shot_alts=['Главный экран посреди промежутка', 'Как выглядит экран во время промежутка',
               'Что разрешено прерывать'],
    why_h='Зачем ещё одно приложение для сна',
    why_p1='В Android уже есть режим сна. На многих телефонах он не срабатывает, пока вы не '
           'откроете приложение, которое им управляет, — или срабатывает, но не вовремя. Режим сна '
           'запланирован как фоновая задача, а выполняются ли фоновые задачи — решает '
           'управление батареей каждого производителя. Если где-то в этой цепочке задачу '
           'откладывают, не будет ни ошибки, ни уведомления — «Не беспокоить» просто не '
           'включается, а эффекты не применяются.',
    why_p2='Gloaming не пользуется фоновой задачей. Он запрашивает разрешение «Будильники и '
           'напоминания» — то самое, которое вы выдаёте в приложении, — и система '
           'гарантирует срабатывание в заданную минуту. У Gloaming собственное правило '
           '«Не беспокоить», и он переключает его сам, так что режим сна наступает '
           'независимо от того, открыто приложение или нет.',
    what_h='Что умеет Gloaming',
    feats=[
        ('24-часовой циферблат',
         'Один промежуток: тяните любой конец по кругу или коснитесь времени и выберите его '
         'точно. Вы выбираете не вечер, когда ложитесь, а утро, когда хотите проснуться: '
         'выберите субботу — и промежуток продлится с вечера пятницы до утра субботы.'),
        ('Завершение по будильнику',
         'Включите — и промежуток сам подстроится под время вашего будильника, вместо того '
         'чтобы вести два расписания параллельно.'),
        ('Плитка в быстрых настройках с тремя состояниями',
         'Три вида, у каждого одно значение. Песочные часы — режим сна включён, он ждёт своего часа. Галочка — промежуток идёт прямо сейчас. Собственный знак Gloaming — режим сна выключен. Плитка никогда не показывает галочку для того, что ещё не началось.'),
        ('Список исключений на заданное время',
         'Кто может позвонить, кто написать, разговоры, повторные звонки, напоминания, '
         'события календаря, медиа. Экран показывает текущее состояние системы, а не то, '
         'которое приложение включило и считает действующим.'),
        ('Эффекты экрана',
         'Чёрно-белый экран, приглушение обоев, тёмная тема, always-on дисплей. Если '
         'операционная система не позволяет приложению управлять эффектом, переключатель '
         'не показывается вовсе — лучше никакого, чем такой, который врёт.'),
        ('Он проверяет, а не предполагает',
         'Некоторые телефоны замораживают приложения в фоне, и поломка при этом '
         'конкретная: конец промежутка не срабатывает, поэтому режим сна не '
         'заканчивается — всё, что он включил, остаётся включённым уже днём. Gloaming '
         'следит за каждым концом и сообщает, когда тот опоздал, — с кнопкой к настройке '
         'фоновой работы, которая обычно и есть причина. А ещё однократно, через '
         'одиннадцать минут после установки, спрашивает, доставляет ли этот телефон '
         'фоновые сигналы вообще, — и молчит, если всё в порядке.'),
        ('Наблюдение за перезагрузкой',
         'Для телефонов, которые не сообщают приложениям, что телефон перезагрузился: режим '
         'сна остаётся включённым, но уже ничего не сработает. Gloaming это замечает.'),
    ],
    priv_h='Чего Gloaming не делает',
    priv_p='У Gloaming нет разрешения на интернет. Это не обещание не отправлять данные, а ограничение, которое обеспечивает операционная система. '
           'Нет ни аналитики, ни рекламы, ни аккаунтов, ни стороннего кода. Ваше расписание '
           'и собственный журнал приложения остаются на телефоне, а удаление приложения '
           'убирает их.',
    priv_link='Читать политику конфиденциальности',
    req_h='Требования',
    req_p='Android 15 или новее. Два разрешения, оба выдаются из самого приложения: доступ '
          'к политике уведомлений (для «Не беспокоить») и «Будильники и напоминания».',
    foot='Лицензия Apache 2.0 · ',
    foot_src='Код', foot_rel='Релизы', foot_priv='Политика конфиденциальности',
    foot_iss='Сообщить о проблеме',
    p_title='Политика конфиденциальности',
    p_sub='Gloaming для Android',
    p_lede='<strong>Gloaming ничего не собирает, хранит всё на вашем устройстве и не может '
           'никуда отправить данные.</strong> Он не запрашивает разрешение '
           '<code>INTERNET</code>, поэтому у него нет никакого доступа к сети — это не '
           'обещание о намерениях, а ограничение, которое обеспечивает операционная система.',
    p_h1='Что собирается',
    p_1='Ничего. Нет аналитики, отчётов о сбоях, рекламы, сторонних SDK, аккаунтов и входа. '
        'Никакие личные данные или данные устройства не собираются, не передаются, не '
        'продаются и ни с кем не разделяются.',
    p_h2='Что хранится и где',
    p_2='Всё, что Gloaming помнит, остаётся в его собственном приватном хранилище на вашем '
        'телефоне:',
    p_2a='<strong>Ваше расписание и настройки</strong> — промежуток сна, дни, в которые он '
         'действует, список исключений, включённые экранные эффекты, а также выбранные тема '
         'и язык.',
    p_2b='<strong>Журнал</strong> — локальная запись того, что приложение делало каждую '
         'ночь, чтобы проблему можно было объяснить постфактум. Он пишется в собственную '
         'папку приложения и никогда не покидает телефон самостоятельно.',
    p_2c='Удаление Gloaming убирает всё это. <strong>Сбросить Gloaming</strong>, внутри '
         'приложения, очищает данные без удаления.',
    p_h3='Диагностика, которую вы отправляете сами',
    p_3='<strong>Отправить диагностику</strong> собирает журнал, ваше расписание и то, что '
        'система сообщает о правиле «Не беспокоить», в обычный текст и передаёт его в окно '
        '«Поделиться» Android. <strong>Получателя выбираете вы</strong> — почта, сообщение, '
        'заметка себе. Gloaming не передаёт это сам и не имеет такой возможности; если вы '
        'никогда не нажмёте кнопку, ничего и не будет создано. Прочитайте текст перед '
        'отправкой, как и любое сообщение.',
    p_h4='Разрешения, и зачем каждое',
    p_perms=[
        '<strong>Доступ к политике уведомлений</strong> — позволяет приложению создавать и '
        'переключать собственное правило «Не беспокоить». Именно это заставляет режим сна '
        'работать. Оно не даёт доступа к содержимому ваших уведомлений, и Gloaming никогда '
        'их не читает.',
        '<strong>Будильники и напоминания</strong> (<code>SCHEDULE_EXACT_ALARM</code>) — '
        'позволяет начинать и заканчивать ваш промежуток точно в заданное время, пока '
        'приложение закрыто.',
        '<strong>Запуск при старте</strong> (<code>RECEIVE_BOOT_COMPLETED</code>) — '
        'позволяет восстановить ваше расписание после перезагрузки, чтобы перезапуск в два '
        'часа ночи не завершил режим сна молча.',
        '<strong>Изменение системных настроек</strong> (<code>WRITE_SETTINGS</code>) — '
        'необязательное, запрашивается только если вы пользуетесь управлением always-on '
        'дисплеем на телефоне, где эта настройка достижима. Используется исключительно для '
        'записи этого одного ключа.',
        '<code>WRITE_SECURE_SETTINGS</code> — объявлено, но его нельзя выдать при обычной '
        'установке; его выдают только через adb, осознанно, те, кто хочет вендорский путь к '
        'always-on. Без этого разрешения код остаётся неактивным.',
    ],
    p_4b='Gloaming не запрашивает доступа к контактам, местоположению, камере, микрофону, '
         'хранилищу или содержимому ваших сообщений и уведомлений.',
    p_h5='Дети',
    p_5='Gloaming — инструмент общего назначения. Он не предназначен для детей '
        'и не собирает никаких данных — ни о них, ни о ком-то ещё.',
    p_h6='Изменения',
    p_6='Если эта политика когда-нибудь изменится, она изменится здесь, с обновлённой датой '
        'ниже. У приложения открытый код, поэтому любое изменение того, что оно на самом '
        'деле делает, видно в истории коммитов.',
    p_h7='Контакты',
    p_7='Вопросы или сообщение о неточности здесь: создайте issue по адресу',
    p_eff='Действует с ' + EFFECTIVE + '. Код: ',
)


def chrome(lang, up, page):
    """Header: wordmark, language switcher, theme toggle."""
    t = T[lang]
    langs = ''.join(
        f'<a href="{up}{path}{page}"{" aria-current=\"page\"" if code == lang else ""}>'
        f'<span class="lg">{label}</span><span class="sm">{short}</span></a>'
        for code, label, short, path in LANGS)
    return f'''<header class="bar">
  <a class="brand" href="index.html"><img src="{up}icon.png" alt="" width="62" height="62">Gloaming</a>
  <div class="bar-end">
    <nav class="langs" aria-label="Language">{langs}</nav>
    <button class="theme" type="button"
      data-name-system="{t['theme_system']}" data-name-dawn="{t['theme_dawn']}" data-name-dusk="{t['theme_dusk']}"
      data-label-system="{t['theme_system']}" data-label-dawn="{t['theme_dawn']}" data-label-dusk="{t['theme_dusk']}"
      aria-label="{t['theme_system']}">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
        <path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8Z"/>
      </svg><span class="theme-name">{t['theme_system']}</span>
    </button>
  </div>
</header>'''


def shell(lang, title, up, page, body):
    t = T[lang]
    return f'''<!doctype html>
<html lang="{t['htmllang']}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{t['tagline']}">
<link rel="icon" href="{up}icon.png">
{FONTS}
<link rel="stylesheet" href="{up}gloaming.css">
{HEAD_SCRIPT}
</head>
<body>
{chrome(lang, up, page)}
{body}
<div class="viewer" hidden tabindex="-1" role="dialog" aria-modal="true" aria-label="{t['viewer_label']}">
  <button class="vnav prev" type="button" aria-label="{t['viewer_prev']}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m15 5-7 7 7 7"/></svg></button>
  <img alt="">
  <button class="vnav next" type="button" aria-label="{t['viewer_next']}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg></button>
  <p class="vcount" aria-live="polite"></p>
</div>
<script src="{up}gloaming.js"></script>
</body>
</html>
'''


def page_index(lang, up):
    t = T[lang]
    feats = '\n'.join(
        f'    <div class="feat"><h3>{h}</h3><p>{b}</p></div>' for h, b in t['feats'])
    # BOTH themes in the markup, one shown by CSS. The page already carries a
    # Dusk/Dawn toggle, so the screenshots follow it rather than contradicting
    # whichever one the reader is looking at.
    shots = '\n'.join(
        '\n'.join(
            f'    <button class="shot {theme}" type="button" '
            f'data-full="{up}screenshots/{lang}/{theme}/{name}.png" aria-label="{alt}">'
            f'<img src="{up}screenshots/web/{lang}/{theme}/{name}.webp" alt="{alt}" '
            f'loading="lazy"></button>'
            for theme in THEMES)
        for name, alt in zip(SHOTS, t['shot_alts']))
    body = f'''<main>
  <div class="hero">
    <h1>{t['tagline']}</h1>
    <p class="lead">{t['lead']}</p>
    <div class="sweep"></div>
    <div class="cta">
      <a class="btn" href="{GITHUB}/releases">{t['cta_get']}</a>
      <a class="btn ghost" href="{GITHUB}">{t['cta_src']}</a>
    </div>
  </div>

  <div class="shots">
{shots}
  </div>

  <section>
    <h2>{t['why_h']}</h2>
    <p>{t['why_p1']}</p>
    <p>{t['why_p2']}</p>
  </section>

  <section>
    <h2>{t['what_h']}</h2>
    <div class="feats">
{feats}
    </div>
  </section>

  <section>
    <h2>{t['priv_h']}</h2>
    <div class="note"><p>{t['priv_p']}</p>
    <p><a href="privacy-policy.html">{t['priv_link']}</a></p></div>
  </section>

  <section>
    <h2>{t['req_h']}</h2>
    <p>{t['req_p']}</p>
  </section>
</main>

<footer>
  {t['foot']}<a href="{GITHUB}">{t['foot_src']}</a> ·
  <a href="{GITHUB}/releases">{t['foot_rel']}</a> ·
  <a href="privacy-policy.html">{t['foot_priv']}</a> ·
  <a href="{GITHUB}/issues">{t['foot_iss']}</a>
</footer>'''
    return shell(lang, f"Gloaming · {t['tagline']}", up, 'index.html', body)


def page_privacy(lang, up):
    t = T[lang]
    perms = '\n'.join(f'    <li>{p}</li>' for p in t['p_perms'])
    body = f'''<main>
  <h1>{t['p_title']}</h1>
  <p class="lead">{t['p_sub']} · <code>com.jemcik.gloaming</code></p>

  <div class="note"><p>{t['p_lede']}</p></div>

  <section><h2>{t['p_h1']}</h2><p>{t['p_1']}</p></section>

  <section><h2>{t['p_h2']}</h2>
    <p>{t['p_2']}</p>
    <ul><li>{t['p_2a']}</li><li>{t['p_2b']}</li></ul>
    <p>{t['p_2c']}</p>
  </section>

  <section><h2>{t['p_h3']}</h2><p>{t['p_3']}</p></section>

  <section><h2>{t['p_h4']}</h2>
    <ul>
{perms}
    </ul>
    <p>{t['p_4b']}</p>
  </section>

  <section><h2>{t['p_h5']}</h2><p>{t['p_5']}</p></section>
  <section><h2>{t['p_h6']}</h2><p>{t['p_6']}</p></section>
  <section><h2>{t['p_h7']}</h2>
    <p>{t['p_7']} <a href="{GITHUB}/issues">github.com/jemcik/Gloaming/issues</a>.</p>
  </section>
</main>

<footer>{t['p_eff']}<a href="{GITHUB}">github.com/jemcik/Gloaming</a> · Apache License 2.0</footer>'''
    return shell(lang, f"Gloaming · {t['p_title']}", up, 'privacy-policy.html', body)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, 'w', encoding='utf-8').write(text)
    print(os.path.relpath(path, ROOT), f'{len(text.encode()):,} bytes')


if __name__ == '__main__':
    web_copies()
    write(os.path.join(DOCS, 'gloaming.css'), CSS)
    write(os.path.join(DOCS, 'gloaming.js'), JS)
    # Jekyll would otherwise process a directory that also holds DECISIONS.md
    # and play-listing.md. Nothing here needs it.
    write(os.path.join(DOCS, '.nojekyll'), '')
    for lang, _, _short, path in LANGS:
        up = '' if lang == 'en' else '../'
        d = DOCS if lang == 'en' else os.path.join(DOCS, lang)
        write(os.path.join(d, 'index.html'), page_index(lang, up))
        # The English policy KEEPS its address - it is the URL given to Play.
        write(os.path.join(d, 'privacy-policy.html'), page_privacy(lang, up))
