"""Build the Gloaming site into docs/, for GitHub Pages.

Six pages - a landing page and a privacy policy, in English, Ukrainian and
Russian - from ONE template each. Hand-writing six files means six files
drifting: a section added to the English page and forgotten in the other two is
not a thing anyone notices until a Ukrainian reader is missing a paragraph.
Here the structure is written once and the strings are a table, so a missing
translation is a KeyError at build time rather than a hole on a live page.

The palette and the type are lifted from Theme.kt so the site and the app agree.
Two themes, as the app has: the page follows the OS by default and the toggle
overrides it, which is Settings' own Dusk / Dawn / system choice.

FONTS. Neither bundled font has a single Cyrillic glyph - figtree.ttf carries
391 codepoints and baloo2.ttf 856, Latin both. So the Ukrainian and Russian
pages CANNOT be set in Figtree, and the stack names Golos Text after it: the
browser falls back per glyph, so Latin words keep the brand face and Cyrillic
gets a family designed for it, rather than whatever the OS happens to reach for.
The app has the same gap and no such fallback; see the note in the site commit.

URLS ARE LOAD-BEARING. docs/privacy-policy.html is the address given to Google
Play, so that file must keep its name and its place at the root. The translated
copies live under uk/ and ru/ rather than the English one moving.

Run from anywhere:  python3 tools/build_site.py
"""
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
DOCS = os.path.join(ROOT, 'docs')

GITHUB = 'https://github.com/jemcik/Gloaming'
EFFECTIVE = '4 September 2026'

# ── the shared stylesheet ──────────────────────────────────────────────────
# Tokens are Theme.kt's Dawn and Dusk. They were copy-pasted into two pages
# before this file existed, which at six pages would have been twelve copies.
CSS = """/* Generated by tools/build_site.py - edit there, not here. */

:root {
  /* Dawn, from Theme.kt */
  --surface: #FDFDFD;
  --raise:   #E4E5E2;
  --veil:    #DCDEDA;
  --line:    #C5C4BD;
  --outline: #ACACA5;
  --ink:     #1E1B18;
  --ink-mid: #514A43;
  --state:   #435B7A;
  --fill:    #596F8B;
  --on-fill: #FFFFFF;

  /* Arc - the dial's sweep, night to dawn */
  --night: #2F4260;
  --dusk:  #4E6480;
  --ember: #B2622D;
  --dawn:  #F6A06B;

  --body: "Figtree", "Golos Text", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  --wrap: 46rem;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="dawn"]) {
    --surface: #20242A;
    --raise:   #2F353D;
    --veil:    #383E46;
    --line:    #49505A;
    --outline: #61666E;
    --ink:     #EAEBED;
    --ink-mid: #C7CDD7;
    --state:   #B0C3E0;
    --fill:    #566479;
    --on-fill: #DDE9FF;
  }
}

:root[data-theme="dusk"] {
  --surface: #20242A;
  --raise:   #2F353D;
  --veil:    #383E46;
  --line:    #49505A;
  --outline: #61666E;
  --ink:     #EAEBED;
  --ink-mid: #C7CDD7;
  --state:   #B0C3E0;
  --fill:    #566479;
  --on-fill: #DDE9FF;
}

* { box-sizing: border-box; }

html { scroll-behavior: smooth; }
@media (prefers-reduced-motion: reduce) {
  html { scroll-behavior: auto; }
  * { animation: none !important; transition: none !important; }
}

body {
  margin: 0;
  background: var(--surface);
  color: var(--ink);
  font-family: var(--body);
  font-size: 17px;
  line-height: 1.65;
  -webkit-font-smoothing: antialiased;
}

/* ── chrome ── */

.bar {
  display: flex; align-items: center; gap: 1rem;
  max-width: 62rem; margin: 0 auto; padding: 1.1rem 1.5rem;
}
.brand {
  display: flex; align-items: center; gap: .6rem;
  font-weight: 700; font-size: 1.05rem; letter-spacing: -.01em;
  color: var(--ink); text-decoration: none;
}
.brand img { width: 32px; height: 32px; }
.bar-end { margin-left: auto; display: flex; align-items: center; gap: .4rem; }

.langs { display: flex; gap: .15rem; }
.langs a, .theme {
  font: inherit; font-size: .82rem; font-weight: 600;
  color: var(--ink-mid); background: none; border: 1px solid transparent;
  border-radius: 6px; padding: .3rem .55rem; text-decoration: none; cursor: pointer;
}
.langs a:hover, .theme:hover { color: var(--ink); border-color: var(--line); }
.langs a[aria-current="page"] { color: var(--on-fill); background: var(--fill); }
.langs a:focus-visible, .theme:focus-visible {
  outline: 2px solid var(--state); outline-offset: 2px;
}
.theme { display: inline-flex; align-items: center; gap: .35rem; }
.theme svg { width: 15px; height: 15px; }

/* ── layout ── */

main { max-width: var(--wrap); margin: 0 auto; padding: 1.5rem 1.5rem 5rem; }
section { margin-top: 3.25rem; }

h1 {
  font-size: clamp(2rem, 6vw, 2.7rem); font-weight: 700;
  line-height: 1.12; letter-spacing: -.02em; margin: 0;
  text-wrap: balance;
}
h2 {
  font-size: 1.35rem; font-weight: 700; letter-spacing: -.01em;
  margin: 0 0 .9rem; padding-top: 1.5rem; border-top: 1px solid var(--line);
  text-wrap: balance;
}
h3 { font-size: 1rem; font-weight: 700; margin: 0 0 .2rem; }
p { margin: 0 0 1rem; color: var(--ink-mid); }
.lead { font-size: 1.1rem; color: var(--ink); margin-top: 1rem; }
strong { color: var(--ink); font-weight: 600; }
a { color: var(--state); text-underline-offset: 2px; }

/* ── hero ── */

.hero { padding-top: 1.5rem; }
.sweep {
  height: 7px; border-radius: 4px; margin: 1.75rem 0 0;
  background: linear-gradient(90deg, var(--night) 0%, var(--dusk) 42%,
                                     var(--ember) 76%, var(--dawn) 100%);
}
.cta { display: flex; flex-wrap: wrap; gap: .65rem; margin-top: 1.75rem; }
.btn {
  display: inline-block; text-decoration: none; font-weight: 600; font-size: .95rem;
  padding: .6rem 1.15rem; border-radius: 8px;
  background: var(--fill); color: var(--on-fill); border: 1px solid var(--fill);
}
.btn.ghost { background: none; color: var(--ink); border-color: var(--line); }
.btn:focus-visible { outline: 2px solid var(--state); outline-offset: 2px; }

/* ── screenshots ── */

.shots {
  display: grid; grid-template-columns: repeat(3, 1fr); gap: .9rem;
  margin-top: 2.5rem;
}
.shots img {
  width: 100%; display: block; border-radius: 10px;
  border: 1px solid var(--line);
}
@media (max-width: 34rem) { .shots { grid-template-columns: repeat(2, 1fr); } }

/* ── feature list ── */

.feats { display: flex; flex-direction: column; gap: 0; }
.feat { padding: .95rem 0; border-bottom: 1px solid var(--veil); }
.feat:last-child { border-bottom: 0; }
.feat p { margin: 0; font-size: .95rem; }

/* ── notes ── */

.note {
  background: var(--raise); border-radius: 9px; padding: 1.1rem 1.25rem;
  font-size: .98rem;
}
.note p:last-child { margin-bottom: 0; }

ul { padding-left: 1.15rem; margin: 0 0 1rem; }
li { color: var(--ink-mid); margin-bottom: .5rem; }

code {
  font-family: ui-monospace, "SF Mono", Menlo, monospace;
  font-size: .86em; background: var(--raise); color: var(--ink);
  padding: .1em .35em; border-radius: 3px;
}

footer {
  max-width: var(--wrap); margin: 0 auto;
  padding: 1.5rem 1.5rem 4rem; border-top: 1px solid var(--line);
  font-size: .88rem; color: var(--ink-mid);
}
footer a { color: var(--state); }
"""

# ── theme toggle ───────────────────────────────────────────────────────────
# Applied from an inline head script too, so the page never paints the wrong
# theme first. Three states because Settings has three; "system" is a stored
# value like the others rather than the absence of one.
JS = """// Generated by tools/build_site.py - edit there, not here.
(function () {
  var KEY = 'gloaming-theme', ORDER = ['system', 'dawn', 'dusk'];
  function read() {
    try { return localStorage.getItem(KEY) || 'system'; } catch (e) { return 'system'; }
  }
  function apply(v) {
    var r = document.documentElement;
    if (v === 'system') r.removeAttribute('data-theme'); else r.setAttribute('data-theme', v);
  }
  function label(btn, v) {
    btn.setAttribute('aria-label', btn.dataset['label' + v.charAt(0).toUpperCase() + v.slice(1)] || v);
    btn.querySelector('.theme-name').textContent =
      btn.dataset['name' + v.charAt(0).toUpperCase() + v.slice(1)] || v;
  }
  document.addEventListener('DOMContentLoaded', function () {
    var btn = document.querySelector('.theme');
    if (!btn) return;
    var cur = read();
    label(btn, cur);
    btn.addEventListener('click', function () {
      cur = ORDER[(ORDER.indexOf(cur) + 1) % ORDER.length];
      try { localStorage.setItem(KEY, cur); } catch (e) {}
      apply(cur);
      label(btn, cur);
    });
  });
})();
"""

HEAD_SCRIPT = ("<script>(function(){try{var v=localStorage.getItem('gloaming-theme');"
               "if(v&&v!=='system')document.documentElement.setAttribute('data-theme',v);}"
               "catch(e){}})();</script>")

FONTS = ('<link rel="preconnect" href="https://fonts.googleapis.com">'
         '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
         '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?'
         'family=Figtree:wght@400;600;700&family=Golos+Text:wght@400;600;700&display=swap">')

LANGS = [('en', 'EN', ''), ('uk', 'UK', 'uk/'), ('ru', 'RU', 'ru/')]

# ── content ────────────────────────────────────────────────────────────────
# Every string for every page. A language missing a key fails the build.
T = {}

T['en'] = dict(
    htmllang='en',
    tagline='A bedtime app for Android that keeps its own schedule.',
    lead='One sleep window a night — Do Not Disturb and the screen effects that go '
         'with it — driven by exact alarms, so it fires with the app closed.',
    cta_get='Download the APK', cta_src='Source on GitHub',
    theme_system='System', theme_dawn='Dawn', theme_dusk='Dusk',
    shot_alts=['The home screen mid-window', 'How the screen looks during a window',
               'What is allowed to interrupt'],
    why_h='Why it exists',
    why_p1='Android already has a bedtime mode. On a lot of phones it silently never '
           'fires. It is scheduled as a background job, and every vendor’s battery '
           'management gets a say in whether background jobs ever run. When something in '
           'that chain defers it there is no error and no notification — just a screen '
           'that stayed colorful all night.',
    why_p2='Gloaming uses exact alarms instead. They are a separate, user-granted '
           'permission with a scheduling guarantee, and they do not go through the job '
           'scheduler at all. The app holds its own Do Not Disturb rule and flips it from '
           'its own alarms, so bedtime happens whether or not the app is open.',
    what_h='What it does',
    feats=[
        ('A 24-hour dial',
         'One window, dragged at either end. Days are chosen as the mornings you want the '
         'window to end on, so “the weekend” means Saturday and Sunday mornings.'),
        ('It ends at your alarm',
         'Turn it on and the window follows whatever time your alarm is set for, instead '
         'of you keeping two schedules in step.'),
        ('A Quick Settings tile with three states',
         'An hourglass while bedtime is only scheduled, a tick once it is actually '
         'running. A tick sitting there all evening while nothing is happening is the one '
         'thing a tick must not mean.'),
        ('An allowlist for the night',
         'Who can call, who can message, conversations, repeat callers, reminders, '
         'calendar events, media. The screen reports what the system says is in effect, '
         'not what the app believes it asked for.'),
        ('Screen effects, as far as your phone honors them',
         'Grayscale, wallpaper dimming, dark theme, always-on display. Where an effect '
         'does nothing on your device the switch is not drawn at all, rather than '
         'offering one that lies.'),
        ('It watches its own alarms',
         'If the end of a night comes due and does not arrive on time, you are told, with '
         'a button to the setting that usually explains it.'),
        ('A boot watch',
         'For phones that withhold the restart broadcast from apps their launch manager '
         'has decided are unimportant — which otherwise leaves a bedtime app armed with '
         'no alarms behind it.'),
    ],
    priv_h='What it doesn’t do',
    priv_p='Gloaming has no internet permission. Not “does not send data” — it cannot. '
           'There is no analytics, no advertising, no account and no third-party code. '
           'Your schedule and the app’s own log stay on the phone, and uninstalling '
           'removes them.',
    priv_link='Read the privacy policy',
    req_h='Requirements',
    req_p='Android 15 or newer. Two permissions, both granted from inside the app: '
          'notification policy access (for Do Not Disturb) and exact alarms.',
    foot='Apache License 2.0 · ',
    foot_src='Source', foot_rel='Releases', foot_priv='Privacy policy', foot_iss='Report an issue',
    # privacy policy
    p_title='Privacy policy',
    p_sub='Gloaming for Android',
    p_lede='<strong>Gloaming collects nothing, stores everything on your device, and '
           'cannot send data anywhere.</strong> It does not request the <code>INTERNET</code> '
           'permission, so it has no network access of any kind — this is not a promise '
           'about intent, it is a restriction the operating system enforces.',
    p_h1='What is collected',
    p_1='Nothing. There is no analytics, no crash reporting, no advertising, no '
        'third-party SDK, no account and no sign-in. No personal or device data is '
        'gathered, transmitted, sold or shared with anyone.',
    p_h2='What is stored, and where',
    p_2='Everything Gloaming remembers stays in its own private storage on your phone:',
    p_2a='<strong>Your schedule and settings</strong> — the sleep window, the days it '
         'applies to, the interruption allowlist, the screen effects you enabled, and '
         'your theme and language choices.',
    p_2b='<strong>A journal</strong> — an on-device log of what the app did each night, '
         'so a problem can be explained after the fact. It is written to the app’s own '
         'files directory and never leaves the phone on its own.',
    p_2c='Uninstalling Gloaming removes all of it. <strong>Reset Gloaming</strong>, inside '
         'the app, clears it without uninstalling.',
    p_h3='Diagnostics you choose to send',
    p_3='<strong>Send diagnostics</strong> gathers the journal, your schedule and what the '
        'system reports about the app’s Do Not Disturb rule into plain text, and hands '
        'it to Android’s share sheet. <strong>You choose the recipient</strong> — an '
        'email, a message, a note to yourself. Gloaming does not transmit it and has no way '
        'to; if you never use the button, nothing is ever produced. Read the text before '
        'sending it, as you would any message.',
    p_h4='Permissions, and why each exists',
    p_perms=[
        '<strong>Notification policy access</strong> — lets the app create and switch its '
        'own Do Not Disturb rule. This is what makes bedtime work. It grants no access to '
        'the content of your notifications, and Gloaming never reads them.',
        '<strong>Alarms &amp; reminders</strong> (<code>SCHEDULE_EXACT_ALARM</code>) — lets '
        'the app schedule the exact alarms that start and end the night while it is closed.',
        '<strong>Run at startup</strong> (<code>RECEIVE_BOOT_COMPLETED</code>) — lets it '
        'restore your schedule after a restart, so a reboot at 2am does not silently end '
        'bedtime.',
        '<strong>Modify system settings</strong> (<code>WRITE_SETTINGS</code>) — optional, '
        'and requested only if you use the always-on display control on a phone where that '
        'setting is reachable. Used solely to write that one display key.',
        '<code>WRITE_SECURE_SETTINGS</code> — declared but not grantable by an ordinary '
        'install; it can only be granted over adb, deliberately, by someone who wants the '
        'vendor always-on route. Without that grant the code path is inert.',
    ],
    p_4b='Gloaming requests no access to contacts, location, camera, microphone, storage, '
         'or the content of your messages or notifications.',
    p_h5='Children',
    p_5='Gloaming is a general-purpose utility. It is not directed at children, and since '
        'it collects no data it collects none from them either.',
    p_h6='Changes',
    p_6='If this policy ever changes it will change here, with the date below updated. The '
        'app is open source, so any change to what it actually does is visible in the '
        'commit history.',
    p_h7='Contact',
    p_7='Questions, or a report that something here is inaccurate: open an issue at',
    p_eff='Effective ' + EFFECTIVE + '. Source: ',
)

T['uk'] = dict(
    htmllang='uk',
    tagline='Застосунок для сну на Android, який тримає власний розклад.',
    lead='Одне вікно сну на ніч — «Не турбувати» і екранні ефекти, що йдуть із ним, — '
         'на точних будильниках, тож воно спрацьовує із закритим застосунком.',
    cta_get='Завантажити APK', cta_src='Код на GitHub',
    theme_system='Як у системі', theme_dawn='Світла', theme_dusk='Темна',
    shot_alts=['Головний екран посеред вікна', 'Який вигляд має екран під час вікна',
               'Що дозволено переривати'],
    why_h='Навіщо він',
    why_p1='В Android уже є режим сну. На багатьох телефонах він мовчки не спрацьовує. Він '
           'запланований як фонове завдання, а чи виконуються фонові завдання — вирішує '
           'керування батареєю кожного виробника. Якщо десь у цьому ланцюжку завдання '
           'відкладають, не буде ні помилки, ні сповіщення — лише екран, який усю ніч '
           'лишався кольоровим.',
    why_p2='Gloaming натомість використовує точні будильники. Це окремий дозвіл, який надає '
           'користувач, із гарантією спрацювання, і вони взагалі не проходять через '
           'планувальник завдань. Застосунок тримає власне правило «Не турбувати» і '
           'перемикає його своїми ж будильниками, тож режим сну настає незалежно від того, '
           'відкритий застосунок чи ні.',
    what_h='Що він робить',
    feats=[
        ('24-годинний циферблат',
         'Одне вікно, яке тягнеться за обидва кінці. Дні обираються як ранки, якими вікно '
         'має закінчитися, тож «вихідні» означають ранок суботи й неділі.'),
        ('Завершення за будильником',
         'Увімкніть — і вікно саме підлаштується під час вашого будильника, замість того '
         'щоб вести два розклади паралельно.'),
        ('Плитка у швидких налаштуваннях із трьома станами',
         'Пісочний годинник, поки режим лише заплановано, і галочка, коли він справді діє. '
         'Галочка, що стоїть цілий вечір, поки нічого не відбувається, — це саме те, чого '
         'галочка означати не повинна.'),
        ('Список винятків на ніч',
         'Хто може подзвонити, хто написати, розмови, повторні дзвінки, нагадування, події '
         'календаря, медіа. Екран показує те, що система вважає чинним, а не те, що '
         'застосунок гадає, ніби попросив.'),
        ('Ефекти екрана, наскільки їх підтримує ваш телефон',
         'Чорно-білий екран, притемнення шпалер, темна тема, always-on дисплей. Якщо ефект '
         'на вашому пристрої нічого не робить, перемикач не показується взагалі — краще '
         'жодного, ніж такий, що бреше.'),
        ('Він стежить за власними будильниками',
         'Якщо кінець ночі настав, а сигнал не прийшов вчасно, вам про це скажуть — із '
         'кнопкою до налаштування, яке зазвичай це пояснює.'),
        ('Спостереження за перезавантаженням',
         'Для телефонів, які приховують від застосунків сигнал про перезапуск і залишають '
         'режим сну без жодного будильника за ним.'),
    ],
    priv_h='Чого він не робить',
    priv_p='У Gloaming немає дозволу на інтернет. Не «не надсилає дані» — а не може. Немає '
           'ні аналітики, ні реклами, ні акаунтів, ні стороннього коду. Ваш розклад і '
           'власний журнал застосунку лишаються на телефоні, а видалення застосунку '
           'прибирає їх.',
    priv_link='Читати політику приватності',
    req_h='Вимоги',
    req_p='Android 15 або новіший. Два дозволи, обидва надаються з самого застосунку: '
          'доступ до політики сповіщень (для «Не турбувати») і точні будильники.',
    foot='Ліцензія Apache 2.0 · ',
    foot_src='Код', foot_rel='Релізи', foot_priv='Політика приватності',
    foot_iss='Повідомити про проблему',
    p_title='Політика приватності',
    p_sub='Gloaming для Android',
    p_lede='<strong>Gloaming нічого не збирає, зберігає все на вашому пристрої і не може '
           'нікуди надіслати дані.</strong> Він не запитує дозволу <code>INTERNET</code>, '
           'тож не має жодного доступу до мережі — це не обіцянка про наміри, а обмеження, '
           'яке забезпечує операційна система.',
    p_h1='Що збирається',
    p_1='Нічого. Немає аналітики, звітів про збої, реклами, сторонніх SDK, акаунтів і '
        'входу. Жодні особисті дані чи дані пристрою не збираються, не передаються, не '
        'продаються і ні з ким не діляться.',
    p_h2='Що зберігається і де',
    p_2='Усе, що Gloaming пам’ятає, лишається у його власному приватному сховищі на вашому '
        'телефоні:',
    p_2a='<strong>Ваш розклад і налаштування</strong> — вікно сну, дні, у які воно діє, '
         'список винятків, увімкнені екранні ефекти, а також вибрані тема й мова.',
    p_2b='<strong>Журнал</strong> — локальний запис того, що застосунок робив щоночі, щоб '
         'проблему можна було пояснити постфактум. Він пишеться у власну теку застосунку і '
         'ніколи не залишає телефон самостійно.',
    p_2c='Видалення Gloaming прибирає все це. <strong>Скинути Gloaming</strong>, усередині '
         'застосунку, очищає дані без видалення.',
    p_h3='Діагностика, яку ви надсилаєте самі',
    p_3='<strong>Надіслати діагностику</strong> збирає журнал, ваш розклад і те, що система '
        'повідомляє про правило «Не турбувати», у звичайний текст і передає його у вікно '
        'поширення Android. <strong>Одержувача обираєте ви</strong> — пошта, повідомлення, '
        'нотатка собі. Gloaming не передає це сам і не має такої змоги; якщо ви ніколи не '
        'натиснете кнопку, нічого й не буде створено. Прочитайте текст перед надсиланням, '
        'як і будь-яке повідомлення.',
    p_h4='Дозволи, і навіщо кожен',
    p_perms=[
        '<strong>Доступ до політики сповіщень</strong> — дозволяє застосунку створювати і '
        'перемикати власне правило «Не турбувати». Саме це змушує режим сну працювати. Він '
        'не дає доступу до вмісту ваших сповіщень, і Gloaming ніколи їх не читає.',
        '<strong>Будильники й нагадування</strong> (<code>SCHEDULE_EXACT_ALARM</code>) — '
        'дозволяє планувати точні будильники, які починають і завершують ніч, поки '
        'застосунок закритий.',
        '<strong>Запуск при старті</strong> (<code>RECEIVE_BOOT_COMPLETED</code>) — '
        'дозволяє відновити ваш розклад після перезавантаження, щоб перезапуск о другій '
        'ночі не завершив режим сну мовчки.',
        '<strong>Зміна системних налаштувань</strong> (<code>WRITE_SETTINGS</code>) — '
        'необов’язковий, запитується лише якщо ви користуєтеся керуванням always-on '
        'дисплеєм на телефоні, де це налаштування доступне. Використовується винятково для '
        'запису цього одного ключа.',
        '<code>WRITE_SECURE_SETTINGS</code> — оголошений, але його неможливо надати при '
        'звичайному встановленні; його видають лише через adb, свідомо, ті, хто хоче '
        'вендорський шлях до always-on. Без цього дозволу код лишається неактивним.',
    ],
    p_4b='Gloaming не запитує доступу до контактів, місцезнаходження, камери, мікрофона, '
         'сховища або вмісту ваших повідомлень чи сповіщень.',
    p_h5='Діти',
    p_5='Gloaming — утиліта загального призначення. Він не призначений для дітей, і '
        'оскільки він не збирає жодних даних, він не збирає їх і в них.',
    p_h6='Зміни',
    p_6='Якщо ця політика колись зміниться, вона зміниться тут, із оновленою датою нижче. '
        'Застосунок має відкритий код, тож будь-яка зміна того, що він насправді робить, '
        'видима в історії комітів.',
    p_h7='Контакти',
    p_7='Питання або повідомлення про неточність тут: створіть issue за адресою',
    p_eff='Чинна з ' + EFFECTIVE + '. Код: ',
)

T['ru'] = dict(
    htmllang='ru',
    tagline='Приложение для сна на Android, которое держит собственное расписание.',
    lead='Одно окно сна за ночь — «Не беспокоить» и экранные эффекты, идущие с ним, — '
         'на точных будильниках, так что оно срабатывает с закрытым приложением.',
    cta_get='Скачать APK', cta_src='Код на GitHub',
    theme_system='Как в системе', theme_dawn='Светлая', theme_dusk='Тёмная',
    shot_alts=['Главный экран посреди окна', 'Как выглядит экран во время окна',
               'Что разрешено прерывать'],
    why_h='Зачем он',
    why_p1='В Android уже есть режим сна. На многих телефонах он молча не срабатывает. Он '
           'запланирован как фоновая задача, а выполняются ли фоновые задачи — решает '
           'управление батареей каждого производителя. Если где-то в этой цепочке задачу '
           'откладывают, не будет ни ошибки, ни уведомления — только экран, который всю '
           'ночь оставался цветным.',
    why_p2='Gloaming вместо этого использует точные будильники. Это отдельное разрешение, '
           'которое выдаёт пользователь, с гарантией срабатывания, и они вообще не проходят '
           'через планировщик задач. Приложение держит собственное правило «Не беспокоить» '
           'и переключает его своими же будильниками, так что режим сна наступает '
           'независимо от того, открыто приложение или нет.',
    what_h='Что он делает',
    feats=[
        ('24-часовой циферблат',
         'Одно окно, которое тянется за оба конца. Дни выбираются как утра, которыми окно '
         'должно закончиться, так что «выходные» — это утро субботы и воскресенья.'),
        ('Завершение по будильнику',
         'Включите — и окно само подстроится под время вашего будильника, вместо того '
         'чтобы вести два расписания параллельно.'),
        ('Плитка в быстрых настройках с тремя состояниями',
         'Песочные часы, пока режим только запланирован, и галочка, когда он действительно '
         'работает. Галочка, стоящая весь вечер, пока ничего не происходит, — это ровно то, '
         'чего галочка означать не должна.'),
        ('Список исключений на ночь',
         'Кто может позвонить, кто написать, разговоры, повторные звонки, напоминания, '
         'события календаря, медиа. Экран показывает то, что система считает действующим, '
         'а не то, что приложение думает, будто запросило.'),
        ('Эффекты экрана, насколько их поддерживает ваш телефон',
         'Чёрно-белый экран, приглушение обоев, тёмная тема, always-on дисплей. Если эффект '
         'на вашем устройстве ничего не делает, переключатель не показывается вовсе — лучше '
         'никакого, чем такой, который врёт.'),
        ('Он следит за собственными будильниками',
         'Если конец ночи наступил, а сигнал не пришёл вовремя, вам об этом скажут — с '
         'кнопкой к настройке, которая обычно это объясняет.'),
        ('Наблюдение за перезагрузкой',
         'Для телефонов, которые скрывают от приложений сигнал о перезапуске и оставляют '
         'режим сна без единого будильника за ним.'),
    ],
    priv_h='Чего он не делает',
    priv_p='У Gloaming нет разрешения на интернет. Не «не отправляет данные» — а не может. '
           'Нет ни аналитики, ни рекламы, ни аккаунтов, ни стороннего кода. Ваше расписание '
           'и собственный журнал приложения остаются на телефоне, а удаление приложения '
           'убирает их.',
    priv_link='Читать политику конфиденциальности',
    req_h='Требования',
    req_p='Android 15 или новее. Два разрешения, оба выдаются из самого приложения: доступ '
          'к политике уведомлений (для «Не беспокоить») и точные будильники.',
    foot='Лицензия Apache 2.0 · ',
    foot_src='Код', foot_rel='Релизы', foot_priv='Политика конфиденциальности',
    foot_iss='Сообщить о проблеме',
    p_title='Политика конфиденциальности',
    p_sub='Gloaming для Android',
    p_lede='<strong>Gloaming ничего не собирает, хранит всё на вашем устройстве и не может '
           'никуда отправить данные.</strong> Он не запрашивает разрешение '
           '<code>INTERNET</code>, поэтому у него нет никакого доступа к сети — это не '
           'обещание о намерениях, а ограничение, которое обеспечивает операционная система.',
    p_h1='Что собирается',
    p_1='Ничего. Нет аналитики, отчётов о сбоях, рекламы, сторонних SDK, аккаунтов и входа. '
        'Никакие личные данные или данные устройства не собираются, не передаются, не '
        'продаются и ни с кем не разделяются.',
    p_h2='Что хранится и где',
    p_2='Всё, что Gloaming помнит, остаётся в его собственном приватном хранилище на вашем '
        'телефоне:',
    p_2a='<strong>Ваше расписание и настройки</strong> — окно сна, дни, в которые оно '
         'действует, список исключений, включённые экранные эффекты, а также выбранные тема '
         'и язык.',
    p_2b='<strong>Журнал</strong> — локальная запись того, что приложение делало каждую '
         'ночь, чтобы проблему можно было объяснить постфактум. Он пишется в собственную '
         'папку приложения и никогда не покидает телефон самостоятельно.',
    p_2c='Удаление Gloaming убирает всё это. <strong>Сбросить Gloaming</strong>, внутри '
         'приложения, очищает данные без удаления.',
    p_h3='Диагностика, которую вы отправляете сами',
    p_3='<strong>Отправить диагностику</strong> собирает журнал, ваше расписание и то, что '
        'система сообщает о правиле «Не беспокоить», в обычный текст и передаёт его в окно '
        '«Поделиться» Android. <strong>Получателя выбираете вы</strong> — почта, сообщение, '
        'заметка себе. Gloaming не передаёт это сам и не имеет такой возможности; если вы '
        'никогда не нажмёте кнопку, ничего и не будет создано. Прочитайте текст перед '
        'отправкой, как и любое сообщение.',
    p_h4='Разрешения, и зачем каждое',
    p_perms=[
        '<strong>Доступ к политике уведомлений</strong> — позволяет приложению создавать и '
        'переключать собственное правило «Не беспокоить». Именно это заставляет режим сна '
        'работать. Оно не даёт доступа к содержимому ваших уведомлений, и Gloaming никогда '
        'их не читает.',
        '<strong>Будильники и напоминания</strong> (<code>SCHEDULE_EXACT_ALARM</code>) — '
        'позволяет планировать точные будильники, которые начинают и заканчивают ночь, пока '
        'приложение закрыто.',
        '<strong>Запуск при старте</strong> (<code>RECEIVE_BOOT_COMPLETED</code>) — '
        'позволяет восстановить ваше расписание после перезагрузки, чтобы перезапуск в два '
        'часа ночи не завершил режим сна молча.',
        '<strong>Изменение системных настроек</strong> (<code>WRITE_SETTINGS</code>) — '
        'необязательное, запрашивается только если вы пользуетесь управлением always-on '
        'дисплеем на телефоне, где эта настройка достижима. Используется исключительно для '
        'записи этого одного ключа.',
        '<code>WRITE_SECURE_SETTINGS</code> — объявлено, но его нельзя выдать при обычной '
        'установке; его выдают только через adb, осознанно, те, кто хочет вендорский путь к '
        'always-on. Без этого разрешения код остаётся неактивным.',
    ],
    p_4b='Gloaming не запрашивает доступа к контактам, местоположению, камере, микрофону, '
         'хранилищу или содержимому ваших сообщений и уведомлений.',
    p_h5='Дети',
    p_5='Gloaming — утилита общего назначения. Он не предназначен для детей, и поскольку он '
        'не собирает никаких данных, он не собирает их и у них.',
    p_h6='Изменения',
    p_6='Если эта политика когда-нибудь изменится, она изменится здесь, с обновлённой датой '
        'ниже. У приложения открытый код, поэтому любое изменение того, что он на самом '
        'деле делает, видно в истории коммитов.',
    p_h7='Контакты',
    p_7='Вопросы или сообщение о неточности здесь: создайте issue по адресу',
    p_eff='Действует с ' + EFFECTIVE + '. Код: ',
)


def chrome(lang, up, page):
    """Header: wordmark, language switcher, theme toggle."""
    t = T[lang]
    langs = ''.join(
        f'<a href="{up}{path}{page}"{" aria-current=\"page\"" if code == lang else ""}>{label}</a>'
        for code, label, path in LANGS)
    return f'''<header class="bar">
  <a class="brand" href="index.html"><img src="{up}icon.png" alt="">Gloaming</a>
  <div class="bar-end">
    <nav class="langs" aria-label="Language">{langs}</nav>
    <button class="theme" type="button"
      data-name-system="{t['theme_system']}" data-name-dawn="{t['theme_dawn']}" data-name-dusk="{t['theme_dusk']}"
      data-label-system="{t['theme_system']}" data-label-dawn="{t['theme_dawn']}" data-label-dusk="{t['theme_dusk']}"
      aria-label="{t['theme_system']}">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
        <path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8Z"/>
      </svg><span class="theme-name">{t['theme_system']}</span>
    </button>
  </div>
</header>'''


def shell(lang, title, up, page, body):
    t = T[lang]
    return f'''<!doctype html>
<html lang="{t['htmllang']}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{t['tagline']}">
<link rel="icon" href="{up}icon.png">
{FONTS}
<link rel="stylesheet" href="{up}gloaming.css">
{HEAD_SCRIPT}
</head>
<body>
{chrome(lang, up, page)}
{body}
<script src="{up}gloaming.js"></script>
</body>
</html>
'''


def page_index(lang, up):
    t = T[lang]
    feats = '\n'.join(
        f'    <div class="feat"><h3>{h}</h3><p>{b}</p></div>' for h, b in t['feats'])
    shots = '\n'.join(
        f'    <img src="{up}screenshots/{n}" alt="{a}">'
        for n, a in zip(['home.png', 'effects.png', 'allowed.png'], t['shot_alts']))
    body = f'''<main>
  <div class="hero">
    <h1>{t['tagline']}</h1>
    <p class="lead">{t['lead']}</p>
    <div class="sweep"></div>
    <div class="cta">
      <a class="btn" href="{GITHUB}/releases">{t['cta_get']}</a>
      <a class="btn ghost" href="{GITHUB}">{t['cta_src']}</a>
    </div>
  </div>

  <div class="shots">
{shots}
  </div>

  <section>
    <h2>{t['why_h']}</h2>
    <p>{t['why_p1']}</p>
    <p>{t['why_p2']}</p>
  </section>

  <section>
    <h2>{t['what_h']}</h2>
    <div class="feats">
{feats}
    </div>
  </section>

  <section>
    <h2>{t['priv_h']}</h2>
    <div class="note"><p>{t['priv_p']}</p>
    <p><a href="privacy-policy.html">{t['priv_link']}</a></p></div>
  </section>

  <section>
    <h2>{t['req_h']}</h2>
    <p>{t['req_p']}</p>
  </section>
</main>

<footer>
  {t['foot']}<a href="{GITHUB}">{t['foot_src']}</a> ·
  <a href="{GITHUB}/releases">{t['foot_rel']}</a> ·
  <a href="privacy-policy.html">{t['foot_priv']}</a> ·
  <a href="{GITHUB}/issues">{t['foot_iss']}</a>
</footer>'''
    return shell(lang, f"Gloaming · {t['tagline']}", up, 'index.html', body)


def page_privacy(lang, up):
    t = T[lang]
    perms = '\n'.join(f'    <li>{p}</li>' for p in t['p_perms'])
    body = f'''<main>
  <h1>{t['p_title']}</h1>
  <p class="lead">{t['p_sub']} · <code>com.jemcik.gloaming</code></p>

  <div class="note"><p>{t['p_lede']}</p></div>

  <section><h2>{t['p_h1']}</h2><p>{t['p_1']}</p></section>

  <section><h2>{t['p_h2']}</h2>
    <p>{t['p_2']}</p>
    <ul><li>{t['p_2a']}</li><li>{t['p_2b']}</li></ul>
    <p>{t['p_2c']}</p>
  </section>

  <section><h2>{t['p_h3']}</h2><p>{t['p_3']}</p></section>

  <section><h2>{t['p_h4']}</h2>
    <ul>
{perms}
    </ul>
    <p>{t['p_4b']}</p>
  </section>

  <section><h2>{t['p_h5']}</h2><p>{t['p_5']}</p></section>
  <section><h2>{t['p_h6']}</h2><p>{t['p_6']}</p></section>
  <section><h2>{t['p_h7']}</h2>
    <p>{t['p_7']} <a href="{GITHUB}/issues">github.com/jemcik/Gloaming/issues</a>.</p>
  </section>
</main>

<footer>{t['p_eff']}<a href="{GITHUB}">github.com/jemcik/Gloaming</a> · Apache License 2.0</footer>'''
    return shell(lang, f"Gloaming · {t['p_title']}", up, 'privacy-policy.html', body)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, 'w', encoding='utf-8').write(text)
    print(os.path.relpath(path, ROOT), f'{len(text.encode()):,} bytes')


if __name__ == '__main__':
    write(os.path.join(DOCS, 'gloaming.css'), CSS)
    write(os.path.join(DOCS, 'gloaming.js'), JS)
    # Jekyll would otherwise process a directory that also holds DECISIONS.md
    # and play-listing.md. Nothing here needs it.
    write(os.path.join(DOCS, '.nojekyll'), '')
    for lang, _, path in LANGS:
        up = '' if lang == 'en' else '../'
        d = DOCS if lang == 'en' else os.path.join(DOCS, lang)
        write(os.path.join(d, 'index.html'), page_index(lang, up))
        # The English policy KEEPS its address - it is the URL given to Play.
        write(os.path.join(d, 'privacy-policy.html'), page_privacy(lang, up))
